### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ssoper** [segmentio/loosely-validate-event#3]
Hey folks, we love the work you've done with this library and love to pull it in. Any chance we could add a license for completeness’ sake? I've already created the PR for your convenience.

https://github.com/segmentio/loosely-validate-event/pull/2

**Comment by stephenmathieson** [comment]
4a709476b48bd91cc32f6c2cb5867d3c9018fd59

**Comment by lubbo** [comment]
@stephenmathieson should the license also be set in the package.json file?
Otherwise [`license-checker`](https://github.com/davglass/license-checker) may reports UNKNOWN when the license is guessed (not retrieved from package.json) and option `--unknown`.
